networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
    networks:
      - dev


  backend:
    build: .
    command: sh -c "alembic upgrade head && python3 createsuperuser.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - dev
